### PR TITLE
Migrate from Test::Unit to Minitest

### PR DESCRIPTION
**Pull request by itsdan**
Use Ruby's standard test library.

### CODE REVIEW

**Comment by marocchino** [comment]
I am OK with minutest but,
- You should change gemspec file also.
- And, It's failing on travis.

**Comment by itsdan** [comment]
Hello, @marocchino!
Thanks for the reply! I've updated .gemspec file. It's now passing on Travis (except for 1.9.3). And maybe it's time to drop 1.9.3 support: if new languages (Address, Name) are added to the gem, files will have to contain encoding comment at the top.

**Comment by rstacruz** [comment]
why is @marocchino not a collaborator yet? :dancer:

**Comment by rstacruz** [comment]
also :+1: for getting rid of that long list of files in the gemspec. #190 would need to update the `rake :build` task too, i think

**Pull request closed without merging**
