### PR TITLE
Make deterministic / repeatedly random using seed

### PR DESCRIPTION
**Pull request by xunker**
This is a work-in-progress to allow FFaker to generate repeatable sequences given the correct seed. This can help with #153 and possibly with parts of #19. I think it's a good start, but I want to get outside opinions before I finish converting all the modules.

It adds:
* `FFaker::Random` class that manages the state of of the Random Number Generator.
* `RandomUtils#fetch_sample` to be used in place of `Array#sample`.
* `RandomUtils#shuffle` to be used in place of `Array#shuffle`.
* `RandomUtils#rand` to be used in place of `rand` or `Kernal.rand`.
* Include RandomUtils in ModuleUtils so FFaker modules have access to the methods and so calls to stdlib `rand` will be sent to RandomUtils#rand instead.
* Updated ArrayUtils to use methods in RandomUtils.
* `DeterministicHelper` (in helper.rb) to give methods to easily test the determinability of FFaker module methods.
* Additional docs on how to use this in Minitest and Rspec ([Random.md]).

#### TODO LIST (last updated Oct 3, 2016):
* All to-do items are done!
---

To use a specific seed (say, from minitest or rspec), you'll call:

```ruby
FFaker::Random.seed = <the seed>
```

That will store the random seed and build a new RNG based on that seed. When the time comes to reset the RNG back to the initial state you would call:

```ruby
FFaker::Random.reset!
```

Which will reset the RNG back to that starting state using the previously-set seed.

I haven't yet written any code to actually connect this in to rspec or minitest, but it shouldn't be very hard.

---

The things I am not sure of yet are and would like input on:

* ~~Is `fetch` a good name for the _Array#sample_ replacement method? I chose that because there is a similar method in the Faker gem. "deterministic_sample"?~~ Changed `fetch` to `fetch_sample`.

* ~~Is `shuffle` a good name for the  _Array#shuffle_ replacement method? I can't think of anything better.  "deterministic_shuffle"?~~ Going to keep this as `shuffle`.

* ~~Stepping on top of `rand()` with `ModuleUtils#rand` is *very* convenient when it comes to converting the modules, but is it too much magic?~~ Will add documentation to README.

Any other questions or concerns are welcome!

### CODE REVIEW

**Comment by dphurley** [comment]
Very excited about this! Just this week I talked with a co-worker about attempting the same thing. 

Some input on your questions from above...

- Is fetch a good name for the Array#sample replacement method? I chose that because there is a similar method in the Faker gem. "deterministic_sample"?
  - Maybe **fetch_sample()** would be a little more explicit? It would make it pretty clear that you're replacing previous **.sample** calls and wouldn't be confused with Ruby's **Array#fetch**.

- Is shuffle a good name for the Array#shuffle replacement method? I can't think of anything better. "deterministic_shuffle"?
  - It's sufficiently clear to me what this method is doing when I glance at the code. 

- Stepping on top of rand() with ModuleUtils#rand is very convenient when it comes to converting the modules, but is it too much magic?
  - It certainly is magic, but doesn't feel particularly onerous. Especially considering that  **const_missing** is already overridden to enable core functionality, it feels right to keep to the same pattern. Probably worth a mention in the README though once this pull-request is merged.

**Comment by marocchino** [comment]
LGTM! Just resolve confilict to merge. 👍

**Comment by xunker** [comment]
@marocchino Thank you for looking at this. I still need to update the rest of the modules to use the new methods before it is ready to merge, but I will ping you when it's ready :)

**Comment by dphurley** [comment]
@xunker I'd be happy to help out with some of the legwork on this. Let me know.

**Comment by xunker** [comment]
@dphurley I have added a todo-list to the original PR comment and I will try to keep it updated. Feel free to convert any of the modules listed there and make a PR to my fork/branch. Thanks!

The changes should be relatively easy, changing `ary.sample` in to `fetch_sample(ary)`, `ary.shuffle` to `shuffle(ary)` and then adding the appropriate assertions to the test.  Looking at the already-converted address modules will give you an idea.

For testing methods that don't need arguments, you can test a list of them with `assert_methods_are_deterministic`. For methods that need an argument, you can test them with `assert_deterministic`. Both are defined in `helper.rb`. You can also look at the address module tests to see examples.

Also, if you can think of a good way to get around having to put `include DeterministicHelper` in every test file, that'd be great :)

**Comment by hurtstotouchfire** [comment]
@xunker is this sufficiently stable that we could do some testing against this branch? We're currently using `faker` but would happily switch to `ffaker` if this merges. We have a lot of issues with non-deterministic test failures from `faker`.

Also happy to contribute if there's more work to do, but your todo list seems about done.

**Comment by xunker** [comment]
@hurtstotouchfire Thanks for the ping -- I need to merge the most recent master in to it and update it for changes. It's almost 100% ready to go except for that and some docs I need to update first.  Thanks for reminding me I still need to finish this up and get it merged, I'll try to do it ASAP!

**Comment by xunker** [comment]
@hurtstotouchfire I've merged current master in and updated the new modules and tests. You are welcome to test with this branch while it is waiting to be merged -- and please let me know if you find any bugs or issues.

**Comment by xunker** [comment]
@marocchino I think this is ready for a review and merge. There are Hound-CI warnings, but those are from merging current master in to the branch so I've elected to not fix them here.

This PR makes changes to almost every file in the repo so there is a lot to review, though the most important things to review (in my opinion) are:

* The new `random_utils.rb` file (I used to have it as part of module_utils.rb, but broken out so it can be used i n array_utils.rb, too).
* The new `Random` module added to `lib/ffaker.rb`.
* New `DeterministicHelper` (`test/helper.rb`)module used in all the test cases.
* The additional documentation added in `RANDON.md`.

Let me know of any questions you have, or any changes you would like me to make. Thanks for letting me work on this, it's been fun 😃

**Comment by hurtstotouchfire** [comment]
@xunker already started ;) I'll let you know how it goes

**Comment by marocchino** [comment]
LGTM. @ffaker/team any comments?

**Pull request merged**
