### PR TITLE
Add JoJo module

### PR DESCRIPTION
**Pull request by Ar2emis**

### CODE REVIEW

**Review by Volosh1n — APPROVED** [review]

**Review by AlexWayfer — COMMENTED** [review]
For what is this?

**Comment by Ar2emis** [comment]
> For what is this?

Mainly to make testing and development more fun by using bizarre names

**Comment by marocchino** [comment]
Basically, we are welcoming this kind of PR.
I think the first was #224.

**Review by marocchino — APPROVED** [review]
👍🏽

**Pull request merged**
